### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by Md-Mahfuzur-Rahman** [tuya/tuya-home-ios-sdk#6]
Issue is ,

Undefined symbol: _read_keys_from_content
Undefined symbol: _read_keys_from_file
Undefined symbol: _thingctypt_CString
Undefined symbol: _thingctypt_OCString

My environment:
XCode - 14.2 
Mac - intel , Monterey 

Inside POD :
    pod "ThingSmartCryption", :path =>'./'
   pod 'ThingSmartHomeKit', '~> 5.1.0'  

Could you please help ?

**Comment by taojingGino** [comment]
https://developer.tuya.com/cn/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-3-%E4%BD%BF%E7%94%A8%20CocoaPods%20%E9%9B%86%E6%88%90

please check this docment,this error looks like you miss ThingSmartCryption's "build" files
@Md-Mahfuzur-Rahman

**Comment by zlinoliver** [comment]
Hi @Md-Mahfuzur-Rahman , as we haven't received any updates for the suggested solutions from your side for 5 days, will close this issue for now. You can reopen it if you have any further questions. Thanks for your feedbacks!

**Comment by Md-Mahfuzur-Rahman** [comment]
Sorry for late reply. Thank you @taojingGino , with the help of ur reply i solved it.
